// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChcH0UxalprrSd0NryPTXnAKcS7-i7SBc',
    appId: '1:979698199508:web:71ebc1aea6faabe61f4441',
    messagingSenderId: '979698199508',
    projectId: 'doc-udi-f231c',
    authDomain: 'doc-udi-f231c.firebaseapp.com',
    storageBucket: 'doc-udi-f231c.appspot.com',
    measurementId: 'G-8X8CY9B81T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5eSRQcyWDWmANA4IIl5F9VX9HyEUMW-8',
    appId: '1:979698199508:android:6978de30a9b63bc51f4441',
    messagingSenderId: '979698199508',
    projectId: 'doc-udi-f231c',
    storageBucket: 'doc-udi-f231c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT3zQxYFrYv3H0a0pmo2WWtE-oOK4FZ2I',
    appId: '1:979698199508:ios:d877975bc19476ba1f4441',
    messagingSenderId: '979698199508',
    projectId: 'doc-udi-f231c',
    storageBucket: 'doc-udi-f231c.appspot.com',
    iosClientId: '979698199508-eg9m819lqe59n1tmtgh2qpqpd4267feq.apps.googleusercontent.com',
    iosBundleId: 'com.example.vinhack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT3zQxYFrYv3H0a0pmo2WWtE-oOK4FZ2I',
    appId: '1:979698199508:ios:d877975bc19476ba1f4441',
    messagingSenderId: '979698199508',
    projectId: 'doc-udi-f231c',
    storageBucket: 'doc-udi-f231c.appspot.com',
    iosClientId: '979698199508-eg9m819lqe59n1tmtgh2qpqpd4267feq.apps.googleusercontent.com',
    iosBundleId: 'com.example.vinhack',
  );
}
